[
  {
    id: 3,
    created_at: "2024-05-19 02:05:32.40818+00",
    name: "Simple Chicken Salad",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Simple%20Chicken%20Salad/26.jpeg",
    duration: 15,
    servings: 2,
    instructions: [
      "1. Wash the mixed greens under cold water and dry them using a salad spinner or paper towels.",
      "2. Shred the leftover chicken into bite-sized pieces.",
      "3. In a large bowl, combine the mixed greens and shredded chicken.",
      "4. In a small bowl, mix together the salad dressing and yogurt until well combined.",
      "5. Drizzle the dressing mixture over the salad.",
      "6. Finely chop the cilantro and sprinkle it over the salad.",
      "7. Squeeze the juice of one lemon over the salad and toss everything together.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "1a7e2e9c-4d5b-4cc9-adca-90bfa120f9aa",
    ingredients: [
      {
        name: "mixed greens",
        quantity: 1,
        already_have: true,
        displayed_text: "1 bag of mixed greens",
      },
      {
        name: "leftover chicken",
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of shredded leftover chicken",
      },
      {
        name: "salad dressing",
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of salad dressing",
      },
      {
        name: "yogurt",
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon of yogurt",
      },
      {
        name: "cilantro",
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of cilantro",
      },
      {
        name: "lemon",
        quantity: 1,
        already_have: true,
        displayed_text: "Juice of 1 lemon",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 4,
    created_at: "2024-05-19 02:05:32.40818+00",
    name: "Easy Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Easy%20Yogurt%20Parfait/26.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "1. In a bowl, add 1 cup of yogurt.",
      "2. Squeeze the juice of half a lemon into the yogurt and mix well.",
      "3. Layer the yogurt in a glass or bowl.",
      "4. Drizzle 1 tablespoon of honey over the top.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "2b82e9a4-1ea4-41f4-b7ad-6508a5201b45",
    ingredients: [
      {
        name: "yogurt",
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of yogurt",
      },
      {
        name: "lemon",
        quantity: 1,
        already_have: true,
        displayed_text: "Juice of 1/2 lemon",
      },
      {
        name: "honey",
        quantity: 1,
        already_have: false,
        displayed_text: "1 tablespoon of honey",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 5,
    created_at: "2024-05-19 02:05:32.40818+00",
    name: "Egg Salad Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Egg%20Salad%20Sandwich/26.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "1. Place 4 eggs in a saucepan and cover them with cold water.",
      "2. Bring to a boil over medium-high heat and then reduce the heat to low. Cover the saucepan and let the eggs simmer for 12 minutes.",
      "3. Remove the eggs from the saucepan and place them in a bowl of ice water. Let them sit for 5 minutes.",
      "4. Peel the eggs and chop them into small pieces.",
      "5. In a medium bowl, combine the chopped eggs, 2 tablespoons of mayonnaise, and 1 teaspoon of mustard. Mix well.",
      "6. Toast 4 slices of bread if desired.",
      "7. Spread the egg salad mixture evenly over two slices of bread.",
      "8. Top the egg salad with mixed greens and place the other two slices of bread on top.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "3a7ec6b7-8298-43c2-adfc-753b29fa6435",
    ingredients: [
      {
        name: "egg carton",
        quantity: 1,
        already_have: true,
        displayed_text: "4 eggs",
      },
      {
        name: "mayonnaise",
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of mayonnaise",
      },
      {
        name: "mustard",
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon of mustard",
      },
      {
        name: "mixed greens",
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of mixed greens",
      },
      {
        name: "bread",
        quantity: 1,
        already_have: false,
        displayed_text: "4 slices of bread",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 6,
    created_at: "2024-05-19 02:05:32.40818+00",
    name: "Cilantro Hummus Dip",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Cilantro%20Hummus%20Dip/26.jpeg",
    duration: 10,
    servings: 4,
    instructions: [
      "1. In a blender or food processor, add 1 cup of hummus.",
      "2. Add a handful of cilantro leaves into the blender.",
      "3. Squeeze the juice of half a lemon into the blender.",
      "4. Blend until the cilantro is well mixed into the hummus.",
      "5. Transfer the cilantro hummus to a serving bowl.",
      "6. Serve with sliced pita bread.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "4c8e7b8d-6b56-4d19-b34d-a28a601d7d5a",
    ingredients: [
      {
        name: "hummus",
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of hummus",
      },
      {
        name: "cilantro",
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of cilantro",
      },
      {
        name: "lemon",
        quantity: 1,
        already_have: true,
        displayed_text: "Juice of 1/2 lemon",
      },
      {
        name: "pita bread",
        quantity: 1,
        already_have: false,
        displayed_text: "1 package of pita bread",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 7,
    created_at: "2024-05-19 02:05:32.40818+00",
    name: "Spicy Mustard Hot Sauce Deviled Eggs",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Spicy%20Mustard%20Hot%20Sauce%20Deviled%20Eggs/26.jpeg",
    duration: 30,
    servings: 12,
    instructions: [
      "1. Place 6 eggs in a saucepan and cover them with cold water.",
      "2. Bring to a boil over medium-high heat, then reduce the heat to low. Cover the saucepan and let the eggs simmer for 12 minutes.",
      "3. Remove the eggs from the saucepan and place them in a bowl of ice water. Let them sit for 5 minutes.",
      "4. Peel the eggs and slice them in half lengthwise.",
      "5. Remove the yolks and place them in a medium bowl.",
      "6. Mash the yolks with a fork and mix in 2 tablespoons of mayonnaise, 1 tablespoon of mustard, and 1/2 teaspoon of hot sauce until smooth.",
      "7. Spoon the yolk mixture back into the egg whites.",
      "8. Sprinkle a pinch of paprika on top as garnish.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "5f9b3c28-d1d5-4f06-8bad-578a8270b256",
    ingredients: [
      {
        name: "egg carton",
        quantity: 1,
        already_have: true,
        displayed_text: "6 eggs",
      },
      {
        name: "mayonnaise",
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of mayonnaise",
      },
      {
        name: "mustard",
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon of mustard",
      },
      {
        name: "hot sauce",
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 teaspoon of hot sauce",
      },
      {
        name: "paprika",
        quantity: 1,
        already_have: false,
        displayed_text: "A pinch of paprika",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 8,
    created_at: "2024-05-19 03:16:44.719864+00",
    name: "Chicken Salad Wrap",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Chicken%20Salad%20Wrap/28.jpeg",
    duration: 15,
    servings: 2,
    instructions: [
      "Wash the lettuce leaves thoroughly and pat them dry with a paper towel.",
      "In a mixing bowl, combine the shredded cooked chicken and mayonnaise. Mix well until the chicken is fully coated.",
      "Chop the pickles into small pieces and add them to the chicken mixture. Stir to combine.",
      "Place a large lettuce leaf on a clean plate and spoon some of the chicken mixture onto the center of the leaf.",
      "Roll the lettuce leaf around the chicken mixture to form a wrap. Secure with a toothpick, if necessary.",
      "Repeat the process to make additional wraps.",
      "Serve immediately and enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "123e4567e89b12d3a4560001",
    ingredients: [
      {
        name: "lettuce",
        quantity: 6,
        already_have: true,
        displayed_text: "large lettuce leaves",
      },
      {
        name: "cooked chicken",
        quantity: 1,
        already_have: true,
        displayed_text: "cup shredded cooked chicken",
      },
      {
        name: "mayonnaise",
        quantity: 2,
        already_have: true,
        displayed_text: "tablespoons of mayonnaise",
      },
      {
        name: "pickles",
        quantity: 3,
        already_have: true,
        displayed_text: "small pickles (chopped)",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 9,
    created_at: "2024-05-19 03:16:44.719864+00",
    name: "Broccoli and Cheese Omelette",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Broccoli%20and%20Cheese%20Omelette/28.jpeg",
    duration: 20,
    servings: 1,
    instructions: [
      "Wash the broccoli thoroughly and chop it into small pieces.",
      "Crack the eggs into a bowl and whisk them until well beaten.",
      "Melt the butter in a non-stick skillet over medium heat.",
      "Add the chopped broccoli to the skillet and sauté for 4-5 minutes until tender.",
      "Pour the beaten eggs over the broccoli in the skillet.",
      "Allow the eggs to cook undisturbed for about 2-3 minutes until they start to set around the edges.",
      "Sprinkle the shredded cheese evenly over the eggs.",
      "Using a spatula, fold one side of the omelette over the other to create a half-moon shape.",
      "Cook for another 1-2 minutes until the cheese is melted and the eggs are fully set.",
      "Carefully slide the omelette onto a plate and serve hot.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "123e4567e89b12d3a4560002",
    ingredients: [
      {
        name: "eggs",
        quantity: 2,
        already_have: true,
        displayed_text: "large eggs",
      },
      {
        name: "broccoli",
        quantity: 0.5,
        already_have: true,
        displayed_text: "cup of chopped broccoli",
      },
      {
        name: "cheese",
        quantity: 0.25,
        already_have: true,
        displayed_text: "cup of shredded cheese (can use cream cheese)",
      },
      {
        name: "butter",
        quantity: 1,
        already_have: true,
        displayed_text: "tablespoon of butter",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 10,
    created_at: "2024-05-19 03:16:44.719864+00",
    name: "Fruit and Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Fruit%20and%20Yogurt%20Parfait/28.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "In a mixing bowl, combine the yogurt and orange juice. Stir well until smooth.",
      "Take two serving glasses and start layering the ingredients.",
      "Spoon a layer of yogurt mixture into the bottom of each glass.",
      "Add a layer of mixed fruits (if using), followed by a dollop of jam.",
      "Repeat the layers until all ingredients are used up, finishing with a layer of yogurt on top.",
      "Drizzle the maple syrup over the top of each parfait.",
      "Serve immediately and enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "123e4567e89b12d3a4560003",
    ingredients: [
      {
        name: "yogurt",
        quantity: 2,
        already_have: true,
        displayed_text: "cups of yogurt",
      },
      {
        name: "orange juice",
        quantity: 2,
        already_have: true,
        displayed_text: "tablespoons of orange juice",
      },
      {
        name: "jam",
        quantity: 2,
        already_have: true,
        displayed_text: "tablespoons of jam (any flavor)",
      },
      {
        name: "maple syrup",
        quantity: 2,
        already_have: true,
        displayed_text: "tablespoons of maple syrup",
      },
      {
        name: "mixed fruits",
        quantity: 1,
        already_have: false,
        displayed_text: "cup of mixed fresh or canned fruits (optional)",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 11,
    created_at: "2024-05-19 03:16:44.719864+00",
    name: "Hummus and Veggie Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Hummus%20and%20Veggie%20Sandwich/28.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "Take two slices of bread and lay them flat on a clean surface.",
      "Spread a tablespoon of hummus evenly over each slice of bread.",
      "Place a leaf of lettuce on each slice of bread.",
      "Chop the celery into small pieces and sprinkle it over the lettuce.",
      "Slice the pickle and layer the slices on top of the celery.",
      "Press the two slices of bread together to make a sandwich.",
      "Cut the sandwich in half if desired, and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "123e4567e89b12d3a4560004",
    ingredients: [
      {
        name: "bread",
        quantity: 2,
        already_have: false,
        displayed_text: "slices of bread",
      },
      {
        name: "hummus",
        quantity: 2,
        already_have: true,
        displayed_text: "tablespoons of hummus",
      },
      {
        name: "lettuce",
        quantity: 2,
        already_have: true,
        displayed_text: "leaves of lettuce",
      },
      {
        name: "celery",
        quantity: 1,
        already_have: true,
        displayed_text: "stalk of celery (chopped)",
      },
      {
        name: "pickles",
        quantity: 1,
        already_have: true,
        displayed_text: "pickle (sliced)",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 12,
    created_at: "2024-05-19 03:16:44.719864+00",
    name: "Veggie Stir-Fry",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/Veggie%20Stir-Fry/28.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "Wash the broccoli and celery thoroughly. Cut the broccoli into florets and slice the celery.",
      "Heat olive oil in a large skillet over medium-high heat.",
      "Add the broccoli and celery to the skillet and sauté for 5-7 minutes until tender-crisp.",
      "Pour the soy sauce over the veggies and stir to coat evenly.",
      "Continue to cook for another 2-3 minutes until the soy sauce is mostly absorbed.",
      "Serve the stir-fry hot as a main or side dish.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "123e4567e89b12d3a4560005",
    ingredients: [
      {
        name: "broccoli",
        quantity: 1,
        already_have: true,
        displayed_text: "cup of broccoli florets",
      },
      {
        name: "celery",
        quantity: 2,
        already_have: true,
        displayed_text: "stalks of celery (sliced)",
      },
      {
        name: "soy sauce",
        quantity: 3,
        already_have: true,
        displayed_text: "tablespoons of soy sauce",
      },
      {
        name: "olive oil",
        quantity: 2,
        already_have: false,
        displayed_text: "tablespoons of olive oil",
      },
    ],
    description: null,
    total_calories: null,
  },
  {
    id: 13,
    created_at: "2024-05-19 06:28:03.460297+00",
    name: "Chicken Salad Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/29/Chicken%20Salad%20Sandwich.jpeg",
    duration: 30,
    servings: 2,
    instructions: [
      "1. Before starting, make sure your hands and surfaces are clean.",
      "2. To prepare the chicken, grill it for about 6-8 minutes on each side or until cooked through. You can season with a bit of salt and pepper if desired.",
      "3. Once the chicken is cooked, let it cool for a few minutes and then dice it into small pieces.",
      "4. In a bowl, mix the diced chicken with the salad dressing. Make sure all pieces are well coated.",
      "5. Wash the lettuce leaves thoroughly under running water and pat them dry with a paper towel.",
      "6. Take two slices of bread and place lettuce leaves on each slice.",
      "7. Evenly distribute the chicken salad mixture over the lettuce leaves.",
      "8. Place the remaining slices of bread on top to make the sandwich complete.",
      "9. Your Chicken Salad Sandwich is now ready to serve. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "93f2e2ef-6689-4eb5-a4a3-1a5e1cd3584d",
    ingredients: [
      {
        name: "chicken",
        calories: 220,
        quantity: 1,
        already_have: true,
        displayed_text: "1 grilled chicken breast",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 4,
        already_have: true,
        displayed_text: "4 leaves of lettuce",
      },
      {
        name: "bread",
        calories: 140,
        quantity: 4,
        already_have: true,
        displayed_text: "4 slices of bread",
      },
      {
        name: "salad dressing",
        calories: 85,
        quantity: 3,
        already_have: true,
        displayed_text: "3 tablespoons of salad dressing",
      },
    ],
    description:
      "A simple and delicious chicken salad sandwich made with juicy chicken, crisp lettuce, and a tangy salad dressing.",
    total_calories: 450,
  },
  {
    id: 24,
    created_at: "2024-05-19 13:27:30.210246+00",
    name: "Creamy Hummus Dip",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/35/Creamy%20Hummus%20Dip.jpeg",
    duration: 5,
    servings: 4,
    instructions: [
      "1. Open the container of hummus.",
      "2. If you like, you can transfer the hummus to a serving bowl for a nicer presentation.",
      "3. Garnish with a drizzle of olive oil and a sprinkle of paprika or fresh herbs if desired.",
      "4. Serve the hummus with your favorite snacks like pita bread, chips, or sliced vegetables. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "c3d4e5f6-g8h9-47i1-0123-5abcd6ef7gh8",
    ingredients: [
      {
        name: "hummus",
        calories: 200,
        quantity: 1,
        already_have: true,
        displayed_text: "1 container of hummus",
      },
    ],
    description:
      "A smooth and creamy hummus dip to enjoy with snacks or as a spread.",
    total_calories: 200,
  },
  {
    id: 14,
    created_at: "2024-05-19 06:28:03.460297+00",
    name: "Scrambled Eggs with Lemon Cilantro",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/29/Scrambled%20Eggs%20with%20Lemon%20Cilantro.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "1. Crack the eggs into a bowl. Add a pinch of salt and whisk them together until well mixed.",
      "2. Heat a non-stick skillet over medium heat. Add a small amount of butter or oil and let it melt.",
      "3. Pour the whisked eggs into the skillet and let them cook for a few seconds undisturbed.",
      "4. Gently stir the eggs using a spatula, pushing them from the edges toward the center. Continue to cook until they are softly set and slightly runny in parts.",
      "5. Zest the lemon using a grater and sprinkle over the scrambled eggs.",
      "6. Chop the cilantro finely and sprinkle it over the eggs, mixing it lightly.",
      "7. Remove the scrambled eggs from the skillet while still slightly undercooked as they will continue to cook with the residual heat.",
      "8. Serve immediately with a slice of bread or on its own.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "adaf0e57-8938-449c-bf2e-1663c8f40711",
    ingredients: [
      {
        name: "eggs",
        calories: 280,
        quantity: 4,
        already_have: true,
        displayed_text: "4 eggs",
      },
      {
        name: "lemon",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1 lemon, zested",
      },
      {
        name: "cilantro",
        calories: 2,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of chopped cilantro",
      },
    ],
    description:
      "A flavorful scrambled eggs recipe with a hint of lemon and fresh cilantro, perfect for a quick and nutritious breakfast.",
    total_calories: 250,
  },
  {
    id: 15,
    created_at: "2024-05-19 06:28:03.460297+00",
    name: "Hummus and Veggie Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/29/Hummus%20and%20Veggie%20Sandwich.jpeg",
    duration: 15,
    servings: 2,
    instructions: [
      "1. Start by washing the lettuce leaves and patting them dry with a paper towel.",
      "2. Chop the cilantro finely and set it aside.",
      "3. Take two slices of bread and spread 2 tablespoons of hummus evenly on each slice.",
      "4. Place the lettuce leaves on top of the hummus spread on each slice of bread.",
      "5. Sprinkle the chopped cilantro over the lettuce.",
      "6. Add a slice of lemon on each sandwich for a hint of freshness.",
      "7. Close the sandwiches with the remaining slices of bread, pressing gently to ensure everything stays in place.",
      "8. Cut the sandwiches in half if desired and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "7794b524-149f-45b6-aa6e-093e533e0ed4",
    ingredients: [
      {
        name: "hummus",
        calories: 130,
        quantity: 4,
        already_have: true,
        displayed_text: "4 tablespoons of hummus",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 4,
        already_have: true,
        displayed_text: "4 leaves of lettuce",
      },
      {
        name: "bread",
        calories: 140,
        quantity: 4,
        already_have: true,
        displayed_text: "4 slices of bread",
      },
      {
        name: "lemon",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "2 slices of lemon",
      },
      {
        name: "cilantro",
        calories: 2,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of chopped cilantro",
      },
    ],
    description:
      "A nutritious and easy-to-make sandwich featuring hummus spread and fresh vegetables.",
    total_calories: 350,
  },
  {
    id: 16,
    created_at: "2024-05-19 06:28:03.460297+00",
    name: "Yogurt and Fruit Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/29/Yogurt%20and%20Fruit%20Parfait.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "1. Take a clean glass or bowl for the parfait.",
      "2. Add a spoonful of yogurt to the bottom of the glass, spreading it evenly.",
      "3. Add a spoonful of jam over the yogurt layer.",
      "4. Repeat this process, adding another layer of yogurt followed by another layer of jam.",
      "5. If you have fresh fruits, you can add them between the layers or decorated on top.",
      "6. Enjoy your quick and healthy yogurt parfait immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "1628b0e1-ca22-4b32-9d4c-114503805589",
    ingredients: [
      {
        name: "yogurt",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of yogurt",
      },
      {
        name: "jams",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of your favorite jam",
      },
    ],
    description:
      "A quick and healthy yogurt parfait with layers of yogurt and fruit.",
    total_calories: 200,
  },
  {
    id: 17,
    created_at: "2024-05-19 06:28:03.460297+00",
    name: "Spicy Lemon Cilantro Chicken",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/29/Spicy%20Lemon%20Cilantro%20Chicken.jpeg",
    duration: 40,
    servings: 2,
    instructions: [
      "1. In a bowl, mix the juice and zest of the lemon, chopped cilantro, sriracha sauce, and soy sauce to prepare the marinade.",
      "2. Place the chicken breast in the bowl and coat it thoroughly with the marinade. Let it sit for at least 20 minutes.",
      "3. Preheat your grill or skillet to medium-high heat.",
      "4. Grill the marinated chicken for about 6-8 minutes on each side or until fully cooked. The internal temperature should reach 165°F (75°C).",
      "5. Let the chicken rest for a few minutes before slicing.",
      "6. Serve the chicken with lemon wedges and a sprinkle of fresh cilantro on top.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "2bc1dac8-8a9c-492b-b4b1-36277d20f381",
    ingredients: [
      {
        name: "chicken",
        calories: 220,
        quantity: 1,
        already_have: true,
        displayed_text: "1 chicken breast",
      },
      {
        name: "lemon",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1 lemon, juiced and zested",
      },
      {
        name: "cilantro",
        calories: 2,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of chopped cilantro",
      },
      {
        name: "sriracha sauce",
        calories: 30,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons of sriracha sauce",
      },
      {
        name: "soy sauce",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon of soy sauce",
      },
    ],
    description:
      "A flavorful and spicy chicken recipe marinated with lemon, cilantro, and sriracha sauce, perfect for dinner.",
    total_calories: 350,
  },
  {
    id: 18,
    created_at: "2024-05-19 13:23:42.403997+00",
    name: "Egg and Mixed Greens Tortilla Wrap",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/34/Egg%20and%20Mixed%20Greens%20Tortilla%20Wrap.jpeg",
    duration: 15,
    servings: 1,
    instructions: [
      "Step 1: Crack the egg into a bowl. Add 1 tablespoon of milk, a pinch of salt, and a pinch of pepper. Beat the mixture with a fork until well combined.",
      "Step 2: Heat a non-stick pan over medium heat. Pour the egg mixture into the pan, stirring gently with a spatula until the eggs are fully cooked and scrambled.",
      "Step 3: Warm the tortilla in the microwave for about 10 seconds or in a pan for about 30 seconds on each side.",
      "Step 4: Lay the warm tortilla flat on a plate. Add the scrambled eggs in the center.",
      "Step 5: Place a handful of mixed greens on top of the eggs.",
      "Step 6: Drizzle some sriracha over the greens.",
      "Step 7: Roll up the tortilla tightly, starting from one side, ensuring the filling stays inside.",
      "Step 8: Cut the wrap in half and serve immediately. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "520d020b9f4a6bedfd2200c9fc18c2",
    ingredients: [
      {
        name: "eggs",
        calories: 70,
        quantity: 1,
        already_have: false,
        displayed_text: "1 egg",
      },
      {
        name: "mixed greens",
        calories: 10,
        quantity: 1,
        already_have: false,
        displayed_text: "1 handful of mixed greens",
      },
      {
        name: "tortilla",
        calories: 140,
        quantity: 1,
        already_have: false,
        displayed_text: "1 tortilla",
      },
      {
        name: "milk",
        calories: 8,
        quantity: 1,
        already_have: false,
        displayed_text: "1 tablespoon of milk",
      },
      {
        name: "salt",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of salt",
      },
      {
        name: "pepper",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of pepper",
      },
      {
        name: "sriracha",
        calories: 122,
        quantity: 1,
        already_have: true,
        displayed_text: "some sriracha",
      },
    ],
    description:
      "A simple and healthy tortilla wrap filled with scrambled eggs and mixed greens.",
    total_calories: 350,
  },
  {
    id: 19,
    created_at: "2024-05-19 13:23:42.403997+00",
    name: "Yogurt and Pickle Dip",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/34/Yogurt%20and%20Pickle%20Dip.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "Step 1: In a mixing bowl, add 1 cup of yogurt.",
      "Step 2: Finely chop the pickles until you have 2 tablespoons worth, then add them to the bowl of yogurt.",
      "Step 3: Finely chop fresh cilantro to measure 1 tablespoon, then add it to the bowl.",
      "Step 4: Add 1 teaspoon of soy sauce, a pinch of salt, and a pinch of pepper to the bowl.",
      "Step 5: Stir all ingredients together until well combined.",
      "Step 6: Transfer the dip to a serving bowl and garnish with a bit of freshly chopped cilantro.",
      "Step 7: Serve immediately with vegetable sticks or your favorite chips. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "5ef1f7f9e78222f986a602e5cebc68",
    ingredients: [
      {
        name: "yogurt",
        calories: 60,
        quantity: 1,
        already_have: false,
        displayed_text: "1 cup yogurt",
      },
      {
        name: "pickles",
        calories: 5,
        quantity: 2,
        already_have: false,
        displayed_text: "2 tablespoons chopped pickles",
      },
      {
        name: "cilantro",
        calories: 1,
        quantity: 1,
        already_have: false,
        displayed_text: "1 tablespoon chopped fresh cilantro",
      },
      {
        name: "soy sauce",
        calories: 8,
        quantity: 1,
        already_have: false,
        displayed_text: "1 teaspoon soy sauce",
      },
      {
        name: "salt",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of salt",
      },
      {
        name: "pepper",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of pepper",
      },
    ],
    description:
      "A tangy and creamy dip made from yogurt and pickles, perfect to serve with vegetables or chips.",
    total_calories: 100,
  },
  {
    id: 20,
    created_at: "2024-05-19 13:23:42.403997+00",
    name: "Cilantro Yogurt Sauce",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/34/Cilantro%20Yogurt%20Sauce.jpeg",
    duration: 5,
    servings: 2,
    instructions: [
      "Step 1: In a small mixing bowl, add 1/2 cup of yogurt.",
      "Step 2: Finely chop fresh cilantro until you have 2 tablespoons worth, then add it to the bowl of yogurt.",
      "Step 3: Squeeze a lemon and measure 1 tablespoon of lemon juice, then add it to the bowl.",
      "Step 4: Add a pinch of salt and a pinch of pepper to the bowl.",
      "Step 5: Stir all ingredients together until well combined.",
      "Step 6: Transfer the sauce to a serving bowl.",
      "Step 7: Use immediately as a salad dressing, dip, or condiment. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "d8f845a7432d17f6e8e634ba1241da",
    ingredients: [
      {
        name: "yogurt",
        calories: 30,
        quantity: 1,
        already_have: false,
        displayed_text: "1/2 cup yogurt",
      },
      {
        name: "cilantro",
        calories: 1,
        quantity: 1,
        already_have: false,
        displayed_text: "2 tablespoons chopped fresh cilantro",
      },
      {
        name: "lemon juice",
        calories: 4,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon lemon juice",
      },
      {
        name: "salt",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of salt",
      },
      {
        name: "pepper",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a pinch of pepper",
      },
    ],
    description:
      "A versatile and fresh cilantro yogurt sauce perfect for dressing salads or as a dip.",
    total_calories: 50,
  },
  {
    id: 21,
    created_at: "2024-05-19 13:23:42.403997+00",
    name: "Healthy Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/34/Healthy%20Yogurt%20Parfait.jpeg",
    duration: 5,
    servings: 1,
    instructions: [
      "Step 1: Take out a parfait glass or a tall serving glass.",
      "Step 2: Add a layer of 1/4 cup of yogurt to the bottom of the glass.",
      "Step 3: Add a layer of 1/4 cup of mixed fresh fruit on top of the yogurt.",
      "Step 4: Add 1 tablespoon of granola on top of the fruit layer.",
      "Step 5: Repeat the layers by adding another 1/4 cup of yogurt, followed by another 1/4 cup of mixed fresh fruit, and topped off with 1 tablespoon of granola.",
      "Step 6: Serve immediately and enjoy your healthy yogurt parfait.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "b732cd51d6378ea12f483e63e1340a",
    ingredients: [
      {
        name: "yogurt",
        calories: 60,
        quantity: 1,
        already_have: false,
        displayed_text: "1 cup yogurt",
      },
      {
        name: "fruit",
        calories: 60,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 cup mixed fresh fruit",
      },
      {
        name: "granola",
        calories: 60,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons granola",
      },
    ],
    description:
      "A quick and nutritious yogurt parfait layered with fresh fruit and granola.",
    total_calories: 180,
  },
  {
    id: 22,
    created_at: "2024-05-19 13:27:30.210246+00",
    name: "Mixed Greens Salad with Yogurt Dressing",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/35/Mixed%20Greens%20Salad%20with%20Yogurt%20Dressing.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "1. Place the mixed greens in a large bowl.",
      "2. Chop the fresh herbs finely and add them to the bowl with the mixed greens.",
      "3. In a separate small bowl, combine the yogurt and the juice of one lemon. Mix well.",
      "4. Pour the yogurt dressing over the mixed greens and herbs.",
      "5. Gently toss everything together until the greens are well coated with the dressing.",
      "6. Serve immediately and enjoy your refreshing salad!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "a1b2c3d4-e5f6-47g8-9012-3abcd4ef5gh6",
    ingredients: [
      {
        name: "mixed greens",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "1 bag of mixed greens",
      },
      {
        name: "yogurt",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of yogurt",
      },
      {
        name: "herbs",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 handful of herbs",
      },
      {
        name: "lemon",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1 lemon",
      },
    ],
    description:
      "A refreshing salad combining mixed greens with a creamy yogurt dressing.",
    total_calories: 220,
  },
  {
    id: 23,
    created_at: "2024-05-19 13:27:30.210246+00",
    name: "Herb Lemon Chicken",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/35/Herb%20Lemon%20Chicken.jpeg",
    duration: 50,
    servings: 2,
    instructions: [
      "1. Preheat your oven to 375°F (190°C).",
      "2. Place the chicken breasts in a baking dish.",
      "3. Chop the fresh herbs finely.",
      "4. In a small bowl, mix the chopped herbs, the juice of one lemon, and the olive oil together to create a marinade.",
      "5. Pour the marinade over the chicken breasts, ensuring they are fully coated. Let the chicken marinate for at least 15 minutes.",
      "6. Once marinated, bake the chicken in the preheated oven for 25-30 minutes, or until the chicken is fully cooked and no longer pink inside.",
      "7. Remove from the oven and let it rest for a few minutes before serving. Enjoy your delicious, flavorful chicken!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "b2c3d4e5-f6g8-47h9-0123-4abcd5ef6gh7",
    ingredients: [
      {
        name: "chicken",
        calories: 200,
        quantity: 1,
        already_have: true,
        displayed_text: "2 chicken breasts",
      },
      {
        name: "herbs",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 handful of herbs",
      },
      {
        name: "lemon",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1 lemon",
      },
      {
        name: "olive oil",
        calories: 80,
        quantity: 2,
        already_have: false,
        displayed_text: "2 tablespoons of olive oil",
      },
    ],
    description: "Juicy, flavorful chicken marinated with lemon and herbs.",
    total_calories: 300,
  },
  {
    id: 25,
    created_at: "2024-05-19 13:27:30.210246+00",
    name: "Yogurt Herb Dressing",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/35/Yogurt%20Herb%20Dressing.jpeg",
    duration: 5,
    servings: 8,
    instructions: [
      "1. Chop the fresh herbs finely.",
      "2. In a small bowl, mix the yogurt, the juice of one lemon, and the chopped herbs together.",
      "3. Stir until evenly combined.",
      "4. Taste and adjust seasoning if needed. You can add a pinch of salt or pepper for extra flavor.",
      "5. Serve immediately or store in the refrigerator for later use. This dressing is great for salads or as a dip. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "d4e5f6g7-h8i9-47j1-0123-6abcd7ef8gh9",
    ingredients: [
      {
        name: "yogurt",
        calories: 75,
        quantity: 0.5,
        already_have: true,
        displayed_text: "1/2 cup of yogurt",
      },
      {
        name: "herbs",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 handful of fresh herbs",
      },
      {
        name: "lemon",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1 lemon",
      },
    ],
    description:
      "A tangy and flavorful dressing made with yogurt and fresh herbs.",
    total_calories: 30,
  },
  {
    id: 26,
    created_at: "2024-05-19 13:43:07.894959+00",
    name: "Hummus and Veggie Tortilla Wrap",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/37/Hummus%20and%20Veggie%20Tortilla%20Wrap.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "1. Place the tortilla on a clean, flat surface.",
      "2. Spread 2 tablespoons of hummus evenly over the center of the tortilla.",
      "3. Lay a large leaf of lettuce or a handful of shredded lettuce on top of the hummus.",
      "4. Shred 1/2 of a carrot using a grater or a knife, and sprinkle the shredded carrot evenly over the lettuce.",
      "5. Add a handful of fresh cilantro on top of the carrot.",
      "6. Roll the tortilla tightly by folding in the sides first and then rolling from the bottom up.",
      "7. Cut the wrap in half if desired and enjoy your fresh Hummus and Veggie Tortilla Wrap!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "11ec58f622a245cfb1adc2ebf2493d82",
    ingredients: [
      {
        name: "tortilla",
        calories: 120,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tortilla",
      },
      {
        name: "hummus",
        calories: 70,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons hummus",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 large lettuce leaf or a handful of shredded lettuce",
      },
      {
        name: "carrot",
        calories: 25,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 carrot, shredded",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of fresh cilantro",
      },
    ],
    description:
      "A fresh and healthy wrap with hummus, lettuce, carrots, and cilantro.",
    total_calories: 350,
  },
  {
    id: 27,
    created_at: "2024-05-19 13:43:07.894959+00",
    name: "Cilantro Yogurt Dip",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/37/Cilantro%20Yogurt%20Dip.jpeg",
    duration: 5,
    servings: 2,
    instructions: [
      "1. In a small bowl, combine 1/2 cup of yogurt.",
      "2. Chop 1/4 cup of fresh cilantro finely and add it to the yogurt.",
      "3. Add 1 teaspoon of lemonade to the mixture.",
      "4. Stir the ingredients together until they are well mixed.",
      "5. Taste and add salt and pepper if desired.",
      "6. Serve the dip immediately with your favorite veggies or store it in the fridge for later use.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "2d6f3e7adbb5479ca8ecf5f75cd4a8cf",
    ingredients: [
      {
        name: "yogurt",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 cup yogurt",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1/4 cup fresh cilantro, chopped",
      },
      {
        name: "lemonade",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon lemonade",
      },
    ],
    description:
      "A refreshing dip made with yogurt, fresh cilantro, and a touch of lemon juice.",
    total_calories: 60,
  },
  {
    id: 28,
    created_at: "2024-05-19 13:43:07.894959+00",
    name: "Grilled Cheese with Sriracha",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/37/Grilled%20Cheese%20with%20Sriracha.jpeg",
    duration: 15,
    servings: 1,
    instructions: [
      "1. Spread 1/2 tablespoon of butter on one side of each bread slice.",
      "2. Lay one bread slice, buttered side down, in a non-stick skillet.",
      "3. Place 2 slices of cheese on top of the bread in the skillet.",
      "4. Drizzle 1 teaspoon of sriracha sauce over the cheese.",
      "5. Place the second bread slice on top, buttered side up.",
      "6. Turn the heat to medium-low and cook until the bottom slice of bread is golden brown (about 3 minutes).",
      "7. Carefully flip the sandwich and cook until the other side is golden brown and the cheese is melted (another 3 minutes).",
      "8. Remove from the skillet, let cool for a minute, then cut in half and enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "5e47c84e0a0a4485af4d994c4fb7bbf8",
    ingredients: [
      {
        name: "bread",
        calories: 140,
        quantity: 2,
        already_have: true,
        displayed_text: "2 slices of bread",
      },
      {
        name: "cheese",
        calories: 200,
        quantity: 2,
        already_have: true,
        displayed_text: "2 slices of cheese",
      },
      {
        name: "butter",
        calories: 100,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon butter",
      },
      {
        name: "sriracha sauce",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon sriracha sauce",
      },
    ],
    description: "A spicy twist on classic grilled cheese with sriracha sauce.",
    total_calories: 400,
  },
  {
    id: 29,
    created_at: "2024-05-19 13:43:07.894959+00",
    name: "Carrot and Cilantro Salad",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/37/Carrot%20and%20Cilantro%20Salad.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "1. Shred 2 large carrots into a large mixing bowl using a grater or food processor.",
      "2. Chop 1/4 cup of fresh cilantro finely and add it to the bowl with the carrots.",
      "3. Add 2 teaspoons of lemonade to the bowl.",
      "4. Add 1 teaspoon of soy sauce and 1 teaspoon of olive oil to the bowl.",
      "5. Toss all the ingredients together until the salad is well mixed.",
      "6. Serve immediately or let it chill in the fridge for a more refreshing taste.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "8c620ad3cc074a7cb8e3f91ec9040a9c",
    ingredients: [
      {
        name: "carrot",
        calories: 50,
        quantity: 2,
        already_have: true,
        displayed_text: "2 large carrots, shredded",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1/4 cup fresh cilantro, chopped",
      },
      {
        name: "lemonade",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "2 teaspoons lemonade",
      },
      {
        name: "soy sauce",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon of soy sauce",
      },
      {
        name: "olive oil",
        calories: 10,
        quantity: 1,
        already_have: false,
        displayed_text: "1 teaspoon olive oil",
      },
    ],
    description:
      "A simple and refreshing carrot salad with cilantro and a zesty dressing.",
    total_calories: 80,
  },
  {
    id: 30,
    created_at: "2024-05-19 18:27:23.793357+00",
    name: "Veggie Wrap with Hummus",
    image_url:
      '{"data":{"publicUrl":"https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/40/Veggie%20Wrap%20with%20Hummus.jpeg"}}',
    duration: 10,
    servings: 1,
    instructions: [
      "1. Place the tortilla on a clean, flat surface.",
      "2. Spread the hummus evenly over the tortilla using a knife or spoon.",
      "3. Layer the mixed greens, lettuce, and cilantro on top of the hummus.",
      "4. Roll the tortilla tightly to form a wrap. Tuck in the sides as you roll if desired.",
      "5. Slice the wrap in half if you wish, and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "8e4a04a2-cd31-4d38-a6fd-2b5ee65f2db8",
    ingredients: [
      {
        name: "tortilla",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tortilla",
      },
      {
        name: "hummus",
        calories: 70,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons of hummus",
      },
      {
        name: "mixed greens",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 handful of mixed greens",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 leaf of lettuce",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "a few sprigs of cilantro",
      },
    ],
    description:
      "A quick and healthy wrap using fresh vegetables and creamy hummus.",
    total_calories: 350,
  },
  {
    id: 31,
    created_at: "2024-05-19 18:27:23.793357+00",
    name: "Egg and Veggie Salad",
    image_url:
      '{"data":{"publicUrl":"https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/40/Egg%20and%20Veggie%20Salad.jpeg"}}',
    duration: 20,
    servings: 1,
    instructions: [
      "1. Fill a small pot with water and bring it to a boil.",
      "2. Carefully add the egg to the boiling water using a spoon. Boil for 10 minutes to hard-boil the egg.",
      "3. Once the egg is cooked, transfer it to a bowl of cold water to cool. Once cooled, peel the egg and chop it into small pieces.",
      "4. In a large bowl, combine the mixed greens, chopped lettuce, and cilantro.",
      "5. Add the chopped egg to the salad.",
      "6. Squeeze the juice from half a lemon over the salad and toss everything together well.",
      "7. Serve immediately and enjoy your fresh egg and veggie salad.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "5bc6e89b-28fd-4a97-983d-20233566b48c",
    ingredients: [
      {
        name: "egg",
        calories: 70,
        quantity: 1,
        already_have: true,
        displayed_text: "1 egg",
      },
      {
        name: "mixed greens",
        calories: 20,
        quantity: 2,
        already_have: true,
        displayed_text: "2 handfuls of mixed greens",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 leaf of lettuce, chopped",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "a few sprigs of cilantro, chopped",
      },
      {
        name: "lemon",
        calories: 10,
        quantity: 0.5,
        already_have: true,
        displayed_text: "half a lemon, juiced",
      },
    ],
    description:
      "A protein-packed salad with hard-boiled eggs and fresh vegetables.",
    total_calories: 250,
  },
  {
    id: 32,
    created_at: "2024-05-19 18:27:23.793357+00",
    name: "Yogurt Parfait with Jam",
    image_url:
      '{"data":{"publicUrl":"https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/40/Yogurt%20Parfait%20with%20Jam.jpeg"}}',
    duration: 5,
    servings: 1,
    instructions: [
      "1. Take a clean glass or bowl.",
      "2. Spoon half of the yogurt into the glass or bowl.",
      "3. Add 1 tablespoon of jam on top of the yogurt layer.",
      "4. Spoon the remaining yogurt on top of the jam layer.",
      "5. Add the remaining tablespoon of jam on top.",
      "6. Garnish with a few sprigs of cilantro if desired.",
      "7. Serve immediately and enjoy your yogurt parfait.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "aceae204-129a-4c7c-9fbe-1fa30ada88c9",
    ingredients: [
      {
        name: "yogurt",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of yogurt",
      },
      {
        name: "jam",
        calories: 50,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons of jam",
      },
      {
        name: "cilantro",
        calories: 0,
        quantity: 1,
        already_have: true,
        displayed_text: "a few sprigs of cilantro, optional for garnish",
      },
    ],
    description:
      "A quick and easy yogurt parfait with layers of jam for a sweet twist.",
    total_calories: 200,
  },
  {
    id: 33,
    created_at: "2024-05-19 18:27:23.793357+00",
    name: "Citrusy Lemonade",
    image_url:
      '{"data":{"publicUrl":"https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/40/Citrusy%20Lemonade.jpeg"}}',
    duration: 10,
    servings: 2,
    instructions: [
      "1. Roll the lemons on a countertop with slight pressure to help release the juice inside.",
      "2. Cut the lemons in half and squeeze the juice into a bowl or pitcher. Use a strainer if you wish to remove the seeds.",
      "3. Add the orange juice to the lemon juice.",
      "4. Stir in the sugar until it dissolves completely.",
      "5. Add the cold water and mix well.",
      "6. Serve over ice and enjoy your refreshing lemonade.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "c8baebed-dae3-425d-9408-8ec703a4f606",
    ingredients: [
      {
        name: "lemon",
        calories: 40,
        quantity: 2,
        already_have: true,
        displayed_text: "2 lemons",
      },
      {
        name: "orange juice",
        calories: 80,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of orange juice",
      },
      {
        name: "sugar",
        calories: 40,
        quantity: 2,
        already_have: false,
        displayed_text: "2 tablespoons of sugar",
      },
      {
        name: "water",
        calories: 0,
        quantity: 2,
        already_have: false,
        displayed_text: "2 cups of cold water",
      },
    ],
    description: "A refreshing and tangy homemade lemonade.",
    total_calories: 120,
  },
  {
    id: 34,
    created_at: "2024-05-19 18:30:46.299558+00",
    name: "Cheesy Vegetable Stir-fry",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/41/Cheesy%20Vegetable%20Stir-fry.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "Take 1 cup of frozen vegetable mix from the freezer.",
      "Grate 0.5 cup of cheese from the cheese block.",
      "Heat 1 tablespoon of olive oil in a pan over medium heat.",
      "Add the frozen vegetables to the pan and stir occasionally for about 5-7 minutes.",
      "Once the vegetables are cooked and tender, sprinkle grated cheese over the top and let it melt.",
      "Serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "c7c8cfae24b0478abcd6f6f018dc",
    ingredients: [
      {
        name: "frozen vegetables mix",
        calories: 100,
        quantity: 1,
        already_have: true,
        displayed_text: "cup of frozen vegetable mix",
      },
      {
        name: "cheese block",
        calories: 150,
        quantity: 0.5,
        already_have: true,
        displayed_text: "cup of grated cheese",
      },
      {
        name: "olive oil",
        calories: 70,
        quantity: 1,
        already_have: false,
        displayed_text: "tablespoon of olive oil",
      },
    ],
    description:
      "A simple and tasty stir-fry using a mix of frozen vegetables and cheese.",
    total_calories: 320,
  },
  {
    id: 35,
    created_at: "2024-05-19 18:30:46.299558+00",
    name: "Green Peas and Sausage Omelette",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/41/Green%20Peas%20and%20Sausage%20Omelette.jpeg",
    duration: 15,
    servings: 1,
    instructions: [
      "Crack 2 eggs into a bowl and beat them with a fork until well mixed.",
      "Add 0.5 cup of green peas and 0.5 cup of sausage slices to the beaten eggs and mix well.",
      "Heat a non-stick pan over medium heat and pour the egg mixture into the pan.",
      "Cook for 3-5 minutes until the bottom is set, then flip the omelette to cook the other side for another 2-3 minutes.",
      "Serve hot.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "5a7cdfae28b0478bdee5e6f019dc",
    ingredients: [
      {
        name: "sausage slices",
        calories: 100,
        quantity: 0.5,
        already_have: true,
        displayed_text: "cup of sausage slices",
      },
      {
        name: "green peas",
        calories: 50,
        quantity: 0.5,
        already_have: true,
        displayed_text: "cup of green peas",
      },
      {
        name: "eggs",
        calories: 100,
        quantity: 2,
        already_have: true,
        displayed_text: "eggs",
      },
    ],
    description:
      "A protein-rich omelette with green peas and sausage slices, perfect for any meal.",
    total_calories: 250,
  },
  {
    id: 36,
    created_at: "2024-05-19 18:30:46.299558+00",
    name: "Fruit Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/41/Fruit%20Yogurt%20Parfait.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "Take 1 jar of yogurt and open it.",
      "Chop 0.5 green apple and 0.5 red apple into small pieces.",
      "In a glass, layer half of the yogurt, followed by a layer of diced green and red apples.",
      "Add the remaining yogurt on top.",
      "Finish with another layer of diced apples.",
      "Serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "e4f7dfae37b1578cgf78h7f50bfh",
    ingredients: [
      {
        name: "yogurt jars",
        calories: 100,
        quantity: 1,
        already_have: true,
        displayed_text: "jar of yogurt",
      },
      {
        name: "green apples",
        calories: 25,
        quantity: 0.5,
        already_have: true,
        displayed_text: "green apple",
      },
      {
        name: "red apple",
        calories: 25,
        quantity: 0.5,
        already_have: true,
        displayed_text: "red apple",
      },
    ],
    description:
      "A quick and healthy parfait with layers of yogurt, green apple, and red apple.",
    total_calories: 150,
  },
  {
    id: 37,
    created_at: "2024-05-19 18:30:46.299558+00",
    name: "Avocado and Green Pea Spread Toast",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/41/Avocado%20and%20Green%20Pea%20Spread%20Toast.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "Toast 1 slice of bread in a toaster or on a pan until golden brown.",
      "Take 0.5 avocado and scoop the flesh into a bowl.",
      "Add 0.25 cup of green peas to the bowl and mash them together with the avocado until smooth.",
      "Spread the avocado and green pea mixture onto the toasted bread.",
      "Serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "b3g5hfae28j0479hghi2k2h019ec",
    ingredients: [
      {
        name: "green peas",
        calories: 20,
        quantity: 0.25,
        already_have: true,
        displayed_text: "cup of green peas",
      },
      {
        name: "avocado",
        calories: 100,
        quantity: 0.5,
        already_have: true,
        displayed_text: "avocado",
      },
      {
        name: "bread slice",
        calories: 60,
        quantity: 1,
        already_have: false,
        displayed_text: "slice of bread",
      },
    ],
    description:
      "A delicious and nutritious toast spread made from avocado and green peas.",
    total_calories: 180,
  },
  {
    id: 38,
    created_at: "2024-05-19 18:33:03.945971+00",
    name: "Grilled Chicken Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/42/Grilled%20Chicken%20Sandwich.jpeg",
    duration: 20,
    servings: 1,
    instructions: [
      "1. Lay out 2 slices of bread on a clean surface.",
      "2. Spread 1 tablespoon of hummus on each slice of bread.",
      "3. Place a leaf of lettuce on one slice.",
      "4. Spread the shredded cooked chicken evenly over the lettuce.",
      "5. Arrange the sliced bell peppers on top of the chicken.",
      "6. Place the other slice of bread on top, hummus side down, to complete the sandwich.",
      "7. Cut the sandwich in half if desired and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "rec5568bcb4c24e6a824c2bbdf",
    ingredients: [
      {
        name: "cooked chicken",
        calories: 165,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of cooked chicken, shredded",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 leaf of lettuce",
      },
      {
        name: "bell pepper",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 bell pepper, sliced",
      },
      {
        name: "hummus",
        calories: 70,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons of hummus",
      },
      {
        name: "bread",
        calories: 100,
        quantity: 2,
        already_have: true,
        displayed_text: "2 slices of bread",
      },
    ],
    description:
      "A simple and delicious grilled chicken sandwich with a creamy hummus spread.",
    total_calories: 350,
  },
  {
    id: 39,
    created_at: "2024-05-19 18:33:03.945971+00",
    name: "Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/42/Yogurt%20Parfait.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "1. Take 1 cup of yogurt and put it in a serving glass or bowl.",
      "2. If desired, add some fresh fruit like sliced bananas or berries on top of the yogurt.",
      "3. Drizzle a little bit of honey over the yogurt and fruit.",
      "4. Serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "recdef4bcb4c24e6a824c3bbb7",
    ingredients: [
      {
        name: "yogurt",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of yogurt",
      },
    ],
    description:
      "A healthy and refreshing yogurt parfait with layers of fresh fruit and a drizzle of honey.",
    total_calories: 200,
  },
  {
    id: 40,
    created_at: "2024-05-19 18:33:03.945971+00",
    name: "Spicy Chicken Wrap",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/42/Spicy%20Chicken%20Wrap.jpeg",
    duration: 15,
    servings: 1,
    instructions: [
      "1. Lay out a tortilla on a clean surface.",
      "2. Place a leaf of lettuce in the center of the tortilla.",
      "3. Spread the shredded cooked chicken evenly over the lettuce.",
      "4. Arrange the sliced bell peppers on top of the chicken.",
      "5. Drizzle sriracha sauce over the chicken and vegetables.",
      "6. Fold the sides of the tortilla inwards, then roll it up from the bottom to the top to form a wrap.",
      "7. Cut the wrap in half if desired and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "rec2525bcb4c24e6a824c3cccb",
    ingredients: [
      {
        name: "cooked chicken",
        calories: 165,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup of cooked chicken, shredded",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 leaf of lettuce",
      },
      {
        name: "bell pepper",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 bell pepper, sliced",
      },
      {
        name: "sriracha sauce",
        calories: 20,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon of sriracha sauce",
      },
    ],
    description:
      "A tasty chicken wrap with a kick of sriracha for some extra heat.",
    total_calories: 320,
  },
  {
    id: 41,
    created_at: "2024-05-19 18:33:03.945971+00",
    name: "Bell Pepper Omelette",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/42/Bell%20Pepper%20Omelette.jpeg",
    duration: 15,
    servings: 1,
    instructions: [
      "1. Crack the 2 eggs into a bowl and whisk them together until smooth.",
      "2. Dice 1/2 bell pepper into small pieces.",
      "3. Heat a small non-stick pan over medium heat and add a little bit of cooking oil.",
      "4. Add the diced bell pepper to the pan and sauté for 2-3 minutes until softened.",
      "5. Pour the whisked eggs over the bell peppers in the pan.",
      "6. Let the eggs cook for about 2 minutes, until the edges start to set.",
      "7. Use a spatula to gently lift the edges of the omelette and let the uncooked eggs flow underneath.",
      "8. Continue to cook for another 1-2 minutes until the eggs are fully set.",
      "9. Fold the omelette in half and slide it onto a plate.",
      "10. Garnish with some chopped cilantro if desired and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "rec7547bcb4c24e6a824c4dddf",
    ingredients: [
      {
        name: "eggs",
        calories: 140,
        quantity: 2,
        already_have: true,
        displayed_text: "2 eggs",
      },
      {
        name: "bell pepper",
        calories: 15,
        quantity: 1,
        already_have: true,
        displayed_text: "1/2 bell pepper, diced",
      },
    ],
    description:
      "A fluffy omelette filled with sautéed bell peppers and a touch of cheese.",
    total_calories: 300,
  },
  {
    id: 42,
    created_at: "2024-05-19 18:33:03.945971+00",
    name: "Chicken and Bell Pepper Stir-fry",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/42/Chicken%20and%20Bell%20Pepper%20Stir-fry.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "1. Slice the bell peppers into strips.",
      "2. Heat a large non-stick pan or wok over medium-high heat and add a little bit of cooking oil.",
      "3. Add the sliced bell peppers to the pan and stir-fry for 3-4 minutes until they begin to soften.",
      "4. Add the sliced cooked chicken to the pan and continue to stir-fry for another 3-4 minutes until heated through.",
      "5. Pour the soy sauce over the chicken and bell peppers and stir to coat everything evenly.",
      "6. Cook for an additional 1-2 minutes until the soy sauce is heated through and slightly reduced.",
      "7. Serve the stir-fry immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "rec9524bcb4c24e6a824c5eec7",
    ingredients: [
      {
        name: "cooked chicken",
        calories: 330,
        quantity: 2,
        already_have: true,
        displayed_text: "2 cups of cooked chicken, sliced",
      },
      {
        name: "bell pepper",
        calories: 30,
        quantity: 2,
        already_have: true,
        displayed_text: "2 bell peppers, sliced",
      },
      {
        name: "soy sauce",
        calories: 20,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons of soy sauce",
      },
    ],
    description:
      "A quick and easy stir-fry with cooked chicken, bell peppers, and soy sauce.",
    total_calories: 400,
  },
  {
    id: 43,
    created_at: "2024-05-19 19:09:46.802963+00",
    name: "Egg and Vegetable Stir-fry",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/45/Egg%20and%20Vegetable%20Stir-fry.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "1. Wash and slice the yellow bell pepper into thin strips.",
      "2. Chop a small bunch of parsley.",
      "3. Crack the eggs into a bowl and beat them with a fork until they are well mixed.",
      "4. Heat a skillet over medium-high heat and add the butter.",
      "5. Once the butter has melted, add the bell pepper strips to the skillet and sauté for 3-4 minutes until they start to soften.",
      "6. Pour the beaten eggs into the skillet and stir constantly until the eggs are fully cooked, around 2-3 minutes.",
      "7. Add the chopped parsley and soy sauce to the skillet, stirring to combine everything evenly.",
      "8. Cook for an additional 1-2 minutes until everything is heated through.",
      "9. Serve the egg and vegetable stir-fry hot.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "1a2b3c4d5e6f7g8h9i0j12345",
    ingredients: [
      {
        name: "eggs",
        calories: 140,
        quantity: 2,
        already_have: true,
        displayed_text: "2 eggs",
      },
      {
        name: "yellow bell pepper",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "1 yellow bell pepper",
      },
      {
        name: "parsley",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 bunch of parsley",
      },
      {
        name: "soy sauce",
        calories: 10,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons soy sauce",
      },
      {
        name: "butter",
        calories: 90,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon butter",
      },
    ],
    description:
      "A simple and quick stir-fry recipe using fresh vegetables and eggs.",
    total_calories: 250,
  },
  {
    id: 44,
    created_at: "2024-05-19 19:09:46.802963+00",
    name: "Hummus and Veggie Wrap",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/45/Hummus%20and%20Veggie%20Wrap.jpeg",
    duration: 10,
    servings: 1,
    instructions: [
      "1. Wash and slice the yellow bell pepper into thin strips.",
      "2. Wash the lettuce leaves and parsley, and chop the parsley finely.",
      "3. Lay the lettuce leaves flat on a clean surface.",
      "4. Spread the hummus evenly over the lettuce leaves.",
      "5. Place the bell pepper strips and chopped parsley on top of the hummus.",
      "6. Roll the lettuce leaves up tightly to form a wrap.",
      "7. Cut the wrap in half if desired and serve immediately.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "6h7i8j9k0l1m2n3o4p56789q",
    ingredients: [
      {
        name: "hummus",
        calories: 70,
        quantity: 3,
        already_have: true,
        displayed_text: "3 tablespoons hummus",
      },
      {
        name: "yellow bell pepper",
        calories: 25,
        quantity: 0.5,
        already_have: true,
        displayed_text: "1/2 yellow bell pepper",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 2,
        already_have: true,
        displayed_text: "2 large lettuce leaves",
      },
      {
        name: "parsley",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 small bunch parsley",
      },
    ],
    description:
      "A healthy wrap filled with hummus, fresh vegetables, and parsley.",
    total_calories: 200,
  },
  {
    id: 45,
    created_at: "2024-05-19 19:09:46.802963+00",
    name: "Simple Parsley Salad",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/45/Simple%20Parsley%20Salad.jpeg",
    duration: 15,
    servings: 2,
    instructions: [
      "1. Wash and dry the parsley. Remove the leaves from the stems and roughly chop them.",
      "2. Wash and slice the yellow bell pepper into thin strips.",
      "3. In a large bowl, combine the chopped parsley and bell pepper slices.",
      "4. Drizzle the vinaigrette over the salad and toss to coat everything evenly.",
      "5. Serve the salad immediately or refrigerate for up to 2 hours before serving.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "8m9n0o1p2q3r4s5t6u7v890w",
    ingredients: [
      {
        name: "parsley",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 large bunch of parsley",
      },
      {
        name: "yellow bell pepper",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "1 yellow bell pepper",
      },
      {
        name: "vinaigrette",
        calories: 90,
        quantity: 2,
        already_have: true,
        displayed_text: "2 tablespoons vinaigrette",
      },
    ],
    description: "A fresh and simple parsley salad with a tangy vinaigrette.",
    total_calories: 150,
  },
  {
    id: 46,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Chicken Salad Sandwich",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Chicken%20Salad%20Sandwich.jpeg",
    duration: 20,
    servings: 2,
    instructions: [
      "1. In a bowl, combine the shredded leftover chicken, 2 tablespoons of mayo, and 1 tablespoon of mustard. Mix well until the chicken is coated.",
      "2. Lay out 4 slices of bread on a flat surface.",
      "3. Evenly distribute the chicken salad mixture onto 2 of the bread slices.",
      "4. Place a lettuce leaf on top of the chicken salad on each sandwich.",
      "5. Top with the remaining 2 slices of bread.",
      "6. Cut each sandwich in half, if desired, and serve immediately. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "a1b2c3d4e5f6g7h8i9j0k1l2",
    ingredients: [
      {
        name: "leftover chicken",
        calories: 200,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup shredded leftover chicken",
      },
      {
        name: "mayo",
        calories: 100,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons mayo",
      },
      {
        name: "mustard",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 tablespoon mustard",
      },
      {
        name: "lettuce",
        calories: 2,
        quantity: 1,
        already_have: true,
        displayed_text: "2 lettuce leaves",
      },
      {
        name: "bread",
        calories: 120,
        quantity: 1,
        already_have: true,
        displayed_text: "4 slices of bread",
      },
    ],
    description:
      "A tasty and easy-to-make chicken salad sandwich that's perfect for a quick lunch.",
    total_calories: 350,
  },
  {
    id: 47,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Tofu Stir-Fry",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Tofu%20Stir-Fry.jpeg",
    duration: 25,
    servings: 2,
    instructions: [
      "1. Drain and press the tofu to remove excess moisture, then cut into small cubes.",
      "2. Heat a large non-stick skillet over medium-high heat.",
      "3. Add the tofu cubes to the skillet and cook until they are golden and slightly crispy on all sides, about 7-10 minutes.",
      "4. Stir in the sliced carrots and cook for an additional 3-4 minutes until they are slightly tender.",
      "5. Pour in 3 tablespoons of soy sauce, stirring to coat the tofu and carrots evenly.",
      "6. Cook for another 2 minutes, allowing the soy sauce to slightly reduce.",
      "7. Remove from heat and sprinkle with chopped cilantro.",
      "8. Serve hot over rice or on its own. Enjoy!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "b2c3d4e5f6g7h8i9j0k1l2m3",
    ingredients: [
      {
        name: "tofu",
        calories: 150,
        quantity: 1,
        already_have: true,
        displayed_text: "1 block of tofu, cubed",
      },
      {
        name: "soy sauce",
        calories: 30,
        quantity: 1,
        already_have: true,
        displayed_text: "3 tablespoons soy sauce",
      },
      {
        name: "carrots",
        calories: 25,
        quantity: 1,
        already_have: true,
        displayed_text: "1 carrot, sliced",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of cilantro, chopped",
      },
    ],
    description: "A quick and nutritious tofu stir-fry with fresh vegetables.",
    total_calories: 250,
  },
  {
    id: 48,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Yogurt Parfait",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Yogurt%20Parfait.jpeg",
    duration: 10,
    servings: 3,
    instructions: [
      "1. In a medium bowl, mix the diced apples with the juice of 1 lemon to prevent browning.",
      "2. In 3 tall glasses or bowls, layer the yogurt and diced apples.",
      "3. Start with a layer of yogurt at the bottom of each glass, followed by a layer of diced apples.",
      "4. Repeat the layers until all ingredients are used up, finishing with a layer of yogurt on top.",
      "5. Serve immediately or refrigerate until ready to eat. Enjoy your healthy parfait!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "c3d4e5f6g7h8i9j0k1l2m3n4",
    ingredients: [
      {
        name: "yogurt",
        calories: 150,
        quantity: 3,
        already_have: true,
        displayed_text: "3 containers of yogurt",
      },
      {
        name: "apple",
        calories: 100,
        quantity: 2,
        already_have: true,
        displayed_text: "2 apples, diced",
      },
      {
        name: "lemons",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "Juice of 1 lemon",
      },
    ],
    description: "A refreshing and healthy yogurt parfait with fresh fruits.",
    total_calories: 180,
  },
  {
    id: 49,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Apple Carrot Slaw",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Apple%20Carrot%20Slaw.jpeg",
    duration: 15,
    servings: 4,
    instructions: [
      "1. In a large bowl, combine the grated carrot and julienned apples.",
      "2. Add the chopped cilantro and mix well.",
      "3. Pour the juice of 1 lemon over the slaw and toss to combine.",
      "4. Drizzle with 2 tablespoons of your preferred salad dressing.",
      "5. Mix everything together until well coated.",
      "6. Serve immediately or refrigerate until ready to enjoy as a side dish or light snack.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "d4e5f6g7h8i9j0k1l2m3n4o5",
    ingredients: [
      {
        name: "carrots",
        calories: 50,
        quantity: 1,
        already_have: true,
        displayed_text: "2 large carrots, grated",
      },
      {
        name: "apple",
        calories: 100,
        quantity: 2,
        already_have: true,
        displayed_text: "2 apples, julienned",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of cilantro, chopped",
      },
      {
        name: "lemon",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "Juice of 1 lemon",
      },
      {
        name: "salad dressing",
        calories: 100,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons salad dressing",
      },
    ],
    description: "A crisp and tangy apple carrot slaw with a hint of cilantro.",
    total_calories: 120,
  },
  {
    id: 50,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Sriracha-Hummus Toast",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Sriracha-Hummus%20Toast.jpeg",
    duration: 5,
    servings: 1,
    instructions: [
      "1. Toast the slice of bread until it's golden and crispy.",
      "2. Spread 2 tablespoons of hummus evenly on the toasted bread.",
      "3. Drizzle 1 teaspoon of Sriracha sauce over the hummus.",
      "4. Garnish with a few sprigs of cilantro for added flavor.",
      "5. Serve immediately and enjoy your spicy hummus toast!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "e5f6g7h8i9j0k1l2m3n4o5p6",
    ingredients: [
      {
        name: "bread",
        calories: 60,
        quantity: 1,
        already_have: true,
        displayed_text: "1 slice of bread",
      },
      {
        name: "hummus",
        calories: 70,
        quantity: 1,
        already_have: true,
        displayed_text: "2 tablespoons hummus",
      },
      {
        name: "sriracha sauce",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon Sriracha sauce",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "A few sprigs of cilantro",
      },
    ],
    description: "An easy and spicy hummus toast with a kick of Sriracha.",
    total_calories: 200,
  },
  {
    id: 51,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Creamy Lemon Yogurt Dip",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Creamy%20Lemon%20Yogurt%20Dip.jpeg",
    duration: 5,
    servings: 4,
    instructions: [
      "1. In a mixing bowl, combine 2 containers of yogurt, the juice and zest of 1 lemon, and 1 teaspoon soy sauce.",
      "2. Whisk together until smooth and creamy.",
      "3. Stir in a handful of chopped cilantro.",
      "4. Transfer the dip to a serving bowl and garnish with extra lemon zest if desired.",
      "5. Serve immediately with fresh veggies or chips, or refrigerate until ready to enjoy.",
    ],
    likes: 0,
    selected: 0,
    unique_id: "f6g7h8i9j0k1l2m3n4o5p6q7",
    ingredients: [
      {
        name: "yogurt",
        calories: 100,
        quantity: 2,
        already_have: true,
        displayed_text: "2 containers of yogurt",
      },
      {
        name: "lemon",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "Juice and zest of 1 lemon",
      },
      {
        name: "cilantro",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "A handful of cilantro, chopped",
      },
      {
        name: "soy sauce",
        calories: 10,
        quantity: 1,
        already_have: true,
        displayed_text: "1 teaspoon of soy sauce",
      },
    ],
    description: "A creamy and tangy yogurt dip with a hint of lemon.",
    total_calories: 100,
  },
  {
    id: 52,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Orange Juice Smoothie",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Orange%20Juice%20Smoothie.jpeg",
    duration: 5,
    servings: 2,
    instructions: [
      "1. In a blender, combine 1 cup of orange juice, 1 container of yogurt, and 1 sliced carrot.",
      "2. Blend until smooth and creamy.",
      "3. Pour the smoothie into two tall glasses.",
      "4. Serve immediately and enjoy your refreshing drink!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "g7h8i9j0k1l2m3n4o5p6q7r8",
    ingredients: [
      {
        name: "orange juice",
        calories: 110,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup orange juice",
      },
      {
        name: "yogurt",
        calories: 80,
        quantity: 1,
        already_have: true,
        displayed_text: "1 container of yogurt",
      },
      {
        name: "carrots",
        calories: 25,
        quantity: 1,
        already_have: true,
        displayed_text: "1 carrot, sliced",
      },
    ],
    description:
      "A refreshing and healthy smoothie with orange juice and yogurt.",
    total_calories: 250,
  },
  {
    id: 53,
    created_at: "2024-05-20 00:08:05.068223+00",
    name: "Egg and Veggie Scramble",
    image_url:
      "https://kmvqftoebsmmkhxrgdye.supabase.co/storage/v1/object/public/recipe_images/46/Egg%20and%20Veggie%20Scramble.jpeg",
    duration: 10,
    servings: 2,
    instructions: [
      "1. Crack the 2 eggs into a bowl and whisk until well combined.",
      "2. Heat a non-stick skillet over medium heat.",
      "3. Add the diced carrot to the skillet and cook for about 2-3 minutes, or until slightly tender.",
      "4. Pour the beaten eggs into the skillet and stir to scramble.",
      "5. Add the chopped lettuce and continue to cook until the eggs are fully cooked and the veggies are tender, about 3-4 minutes.",
      "6. Remove from heat and serve immediately. Enjoy your healthy scramble!",
    ],
    likes: 0,
    selected: 0,
    unique_id: "h8i9j0k1l2m3n4o5p6q7r8s9",
    ingredients: [
      {
        name: "eggs",
        calories: 140,
        quantity: 2,
        already_have: true,
        displayed_text: "2 large eggs",
      },
      {
        name: "lettuce",
        calories: 5,
        quantity: 1,
        already_have: true,
        displayed_text: "1 cup chopped lettuce",
      },
      {
        name: "carrots",
        calories: 25,
        quantity: 1,
        already_have: true,
        displayed_text: "1 carrot, diced",
      },
    ],
    description: "A quick and healthy egg scramble with fresh veggies.",
    total_calories: 200,
  },
];
